import 'package:flutter/material.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedMed1Widget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedNAMEWidget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedPolice1Widget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedFire1Widget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedFILLUPWITHTHEINFORMATIONNEEDEDWidget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedUntitled11Widget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedPickthebuttonoftherespondersthatyouneedWidget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/ui_20persapp/generatedgooglepixel2xl1widget/generated/GeneratedCONTACTWidget.dart';

/* Frame Google Pixel 2 XL - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel2XL1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 0, 34, 75),
                ),
              ),
              Positioned(
                left: 61.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 27.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 28.0,
                child: GeneratedNAMEWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 28.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 28.0,
                child: GeneratedCONTACTWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 65.0,
                child: GeneratedFILLUPWITHTHEINFORMATIONNEEDEDWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 268.0,
                height: 48.0,
                child: GeneratedPickthebuttonoftherespondersthatyouneedWidget(),
              ),
              Positioned(
                left: 130.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 157.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 158.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 134.0,
                child: GeneratedFire1Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 146.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 229.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 145.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 151.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 154.0,
                child: GeneratedUntitled11Widget(),
              ),
              Positioned(
                left: 45.0,
                top: 647.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 121.0,
                child: GeneratedMed1Widget(),
              ),
              Positioned(
                left: 251.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 131.0,
                child: GeneratedPolice1Widget(),
              )
            ]),
      ),
    ));
  }
}
